"""
Cross-check a hand-transcribed algo.trading_holiday seed against
exchange_calendars.

NOT THE SOURCE OF TRUTH. NSE's annual circular is, and it is transcribed by
hand into seed_<year>.sql because it carries the holiday NAMES, which this
package does not publish. What this script is for is catching a date that was
mistyped or missed in that transcription, which is otherwise silent. For 2026
it produced exactly the same 16 dates as the circular, independently.

RUNS ON A LAPTOP, NEVER IN LAMBDA. exchange_calendars pulls in pandas and
numpy, which is exactly the dependency weight this repo keeps out of its
functions. Nothing at runtime imports it.

    python -m venv .venv && ./.venv/bin/pip install exchange_calendars
    ./.venv/bin/python generate_seed.py 2027 > /tmp/check_2027.sql
    # then diff the dates against seed_2027.sql

The package TRAILS the circular - it gains a year only once a release picks
that circular up - so in December there may be nothing to check against yet.

WHY XBOM AND NOT AN NSE CALENDAR. exchange_calendars ships no NSE calendar;
XBOM (Bombay) is the only Indian one. NSE and BSE observe the same holiday
list for equity and equity derivatives, and XBOM's default session is
09:15-15:30 Asia/Kolkata - identical to SESSION_START/close used across this
repo. Verified against the package on 2026-09-13.

WHAT THIS DOES NOT GIVE YOU, and must be hand-checked each year:

  * Holiday NAMES. XBOM carries its holidays as bare date lists, so every row
    is emitted with description NULL. Filling them in by guessing which
    festival fell on a movable date is how a seed file starts lying.
  * SPECIAL WEEKEND SESSIONS. 2025-02-01 (a Budget Saturday) was a real
    session. Nothing in this system can honour it: every cron is MON-FRI.

Muhurat trading is deliberately out of scope - this system does not trade the
Diwali evening session - so nothing here needs to describe it.
  * ANYTHING PAST THE PACKAGE BOUND. See the check below.
"""

import datetime
import sys

import exchange_calendars as xcals
import pandas as pd

CALENDAR = "XBOM"
# Fixed-date national holidays are the only ones that can be named without
# guessing. Everything else stays NULL on purpose - see the docstring.
CERTAIN_NAMES = {
    (1, 26): "Republic Day",
    (5, 1): "Maharashtra Day",
    (8, 15): "Independence Day",
    (10, 2): "Gandhi Jayanti",
    (12, 25): "Christmas",
}


def holidays(calendar, year):
    """Weekday dates in `year` on which the exchange is closed."""
    start, end = f"{year}-01-01", f"{year}-12-31"
    sessions = calendar.sessions_in_range(start, end)
    weekdays = pd.bdate_range(start, end)
    return sorted(set(weekdays.date) - set(sessions.date))


def main(years):
    calendar = xcals.get_calendar(CALENDAR)
    bound = calendar.last_session.date()
    now = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
    source = f"exchange_calendars {CALENDAR} {xcals.__version__}"

    rows = []
    for year in years:
        if datetime.date(year, 12, 31) > bound:
            # Loud, not a warning buried in output: a short year silently
            # seeded is a system that goes quiet on a date nobody wrote down.
            raise SystemExit(
                f"exchange_calendars {xcals.__version__} covers {CALENDAR} only "
                f"to {bound}, so {year} would be seeded incomplete. Upgrade the "
                f"package and re-run, or drop {year} from the range."
            )
        rows.extend((d, CERTAIN_NAMES.get((d.month, d.day))) for d in holidays(calendar, year))

    print(f"-- algo.trading_holiday seed for {years[0]}-{years[-1]}")
    print(f"-- generated by trading-calendar/generate_seed.py from {source}")
    print(f"-- {len(rows)} weekday holidays. Re-runnable: the upsert is idempotent.")
    print("--")
    print(f"-- COVERAGE ENDS {bound}. After that this table answers 'no row' for")
    print("-- every date, which reads as 'trading day'. Reseed before then.")
    print()
    print("INSERT INTO algo.trading_holiday (trade_date, description, source, updated_at)")
    print("VALUES")
    values = [
        "    (DATE '%s', %s, '%s', %d)"
        % (d, f"'{name}'" if name else "NULL", source, now)
        for d, name in rows
    ]
    print(",\n".join(values))
    print("ON CONFLICT (trade_date) DO UPDATE SET")
    print("    description = EXCLUDED.description,")
    print("    source      = EXCLUDED.source,")
    print("    updated_at  = EXCLUDED.updated_at;")


if __name__ == "__main__":
    main([int(a) for a in sys.argv[1:]] or [datetime.date.today().year])
