-- algo.trading_holiday seed for 2025-2026
-- generated by trading-calendar/generate_seed.py from exchange_calendars XBOM 4.13.2
-- 30 weekday holidays. Re-runnable: the upsert is idempotent.
--
-- COVERAGE ENDS 2026-12-31. After that this table answers 'no row' for
-- every date, which reads as 'trading day'. Reseed before then.

INSERT INTO algo.trading_holiday (trade_date, description, source, updated_at)
VALUES
    (DATE '2025-02-26', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-03-14', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-03-31', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-04-10', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-04-14', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-04-18', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-05-01', 'Maharashtra Day', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-08-15', 'Independence Day', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-08-27', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-10-02', 'Gandhi Jayanti', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-10-21', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-10-22', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-11-05', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2025-12-25', 'Christmas', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-01-15', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-01-26', 'Republic Day', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-03-03', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-03-26', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-03-31', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-04-03', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-04-14', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-05-01', 'Maharashtra Day', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-05-28', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-06-26', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-09-14', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-10-02', 'Gandhi Jayanti', 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-10-20', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-11-10', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-11-24', NULL, 'exchange_calendars XBOM 4.13.2', 1789306603),
    (DATE '2026-12-25', 'Christmas', 'exchange_calendars XBOM 4.13.2', 1789306603)
ON CONFLICT (trade_date) DO UPDATE SET
    description = EXCLUDED.description,
    source      = EXCLUDED.source,
    updated_at  = EXCLUDED.updated_at;
