"""
Dhan Broker Auth — AWS Lambda function

Mints a DhanHQ v2 access token and stores it in SSM Parameter Store, so the
session functions never have to authenticate themselves.

    TOTP ──▶ POST /app/generateAccessToken ──▶ write /algo/dhan/token
                                          └──▶ non-200 or no token ──▶ raise

Trigger: EventBridge Scheduler, cron(0 8 ? * MON-FRI *) Asia/Kolkata — once
each weekday morning, before the 09:15 open. A token lives 24 hours, so the
08:00 token covers the whole session with hours to spare.

Why there is no renew path. /v2/RenewToken exists and would have let one TOTP
login carry a whole week, but it refuses tokens minted this way:

    HTTP 500  DH-905  INVALID_REQUEST
    "Renewal of token not allowed for this token type"

measured 2026-09-10. Renewal is only offered for tokens generated by hand from
Dhan Web. Seeding the parameter once from the web portal and renewing onward
does not rescue it either: the chain breaks every weekend, Monday falls back to
TOTP, and a TOTP-minted token cannot be renewed — so it degrades to this same
design after the first Saturday, having added a manual step on the way. The
branch was built, tested against the live API, and removed. Do not add it back
without new evidence from Dhan.

Weekends are skipped because nothing trades then; Monday simply mints a fresh
token like any other weekday.

Packaging notes:
  - stdlib plus boto3, which is pre-installed in the Lambda Python runtime.
    No layer, no compiled wheels, nothing to build.
  - TOTP is implemented inline (RFC 6238, ~10 lines of hmac/struct) rather
    than pulling in pyotp, and the Dhan endpoint is called with urllib rather
    than the dhanhq SDK, which would drag in pandas/numpy.

Conventions:
  - expires_at is epoch seconds, read from the JWT's own `exp` claim. The
    API also returns an expiryTime string, but it carries no timezone marker
    and is IST — measured 2026-09-10, where exp=1789134580 (13:49:40 UTC) was
    reported as "2026-09-11T19:19:40.019". Parsing it as UTC is 5.5 hours too
    late, so it is logged for diagnostics and never used for arithmetic.
  - Nothing here logs or returns the token. Only its prefix and expiry are
    logged; consumers read the token from the parameter.
"""

import base64
import hashlib
import hmac
import json
import logging
import os
import struct
import time
import urllib.error
import urllib.parse
import urllib.request

import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

GENERATE_URL = os.environ.get(
    "DHAN_GENERATE_TOKEN_URL",
    "https://auth.dhan.co/app/generateAccessToken",
)

TOKEN_PARAMETER_NAME = os.environ.get("TOKEN_PARAMETER_NAME", "/algo/dhan/token")

HTTP_TIMEOUT_SECONDS = int(os.environ.get("HTTP_TIMEOUT_SECONDS", "30"))

# RFC 6238 defaults, which is what Dhan's authenticator enrolment issues.
TOTP_STEP_SECONDS = 30
TOTP_DIGITS = 6

# Reused across warm invocations; creating a boto3 client is not cheap.
_ssm = boto3.client("ssm")


# ---------------------------------------------------------------------------
# TOTP — RFC 6238, SHA-1, 6 digits, 30-second step.
#
# Inlined rather than imported so the package stays stdlib-only. Verified
# against the RFC 6238 test vectors (T=59 -> 287082, T=1111111109 -> 081804)
# using the secret "12345678901234567890".
# ---------------------------------------------------------------------------
def totp_now(secret_b32, at=None):
    """Current TOTP code for a base32 authenticator secret."""
    secret = secret_b32.strip().replace(" ", "").upper()
    secret += "=" * (-len(secret) % 8)
    key = base64.b32decode(secret)

    counter = int(at if at is not None else time.time()) // TOTP_STEP_SECONDS
    digest = hmac.new(key, struct.pack(">Q", counter), hashlib.sha1).digest()

    offset = digest[-1] & 0x0F
    code = struct.unpack(">I", digest[offset : offset + 4])[0] & 0x7FFFFFFF
    return str(code % (10**TOTP_DIGITS)).zfill(TOTP_DIGITS)


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------
def _post(url):
    """POST with an empty body. Returns (status, body_text).

    No Content-Type is set: the endpoint takes its parameters in the query
    string and no body, and declaring application/json on a zero-length body
    is what earned a DH-905 "missing required fields" from Dhan's auth API.
    """
    request = urllib.request.Request(url, method="POST", data=b"")
    try:
        with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
            return response.status, response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode("utf-8", "replace")


def token_expiry_epoch(access_token):
    """Epoch seconds from the JWT's `exp` claim.

    Raises if the claim cannot be read. Storing a token whose expiry we had to
    guess is exactly the silent wrongness the fail-loudly rule exists to stop:
    daily-market-sentiment keys its freshness check off this number, so a wrong
    value would keep a dead token in circulation without anything reporting it.
    """
    try:
        payload = access_token.split(".")[1]
        payload += "=" * (-len(payload) % 4)
        claims = json.loads(base64.urlsafe_b64decode(payload))
    except (IndexError, ValueError, TypeError) as exc:
        raise RuntimeError(
            "Could not decode the access token as a JWT, so its expiry is "
            "unknown. Dhan may have changed the token format — check the "
            "response shape before trusting anything stored."
        ) from exc

    exp = claims.get("exp")
    if not isinstance(exp, int):
        raise RuntimeError(
            "Access token JWT carries no usable `exp` claim (got %r). Refusing "
            "to store a token with a guessed expiry." % (exp,)
        )
    return exp


# ---------------------------------------------------------------------------
# Parameter Store
# ---------------------------------------------------------------------------
def write_stored_token(access_token, expires_at):
    """Persist the token as a single JSON blob.

    One parameter rather than two so the token and its expiry cannot drift
    apart: a torn write leaving a new token beside an old expiry would look
    healthy and behave wrongly.
    """
    record = {
        "access_token": access_token,
        "expires_at": expires_at,
        "refreshed_at": int(time.time()),
        "source": "totp",
    }
    _ssm.put_parameter(
        Name=TOKEN_PARAMETER_NAME,
        Value=json.dumps(record),
        Type="SecureString",
        Overwrite=True,
    )
    return record


# ---------------------------------------------------------------------------
# Dhan auth
# ---------------------------------------------------------------------------
def generate_token(client_id, pin, totp_secret):
    """Mint a token from client id + PIN + TOTP.

    This is the only way in, so any failure here is terminal and raises.
    """
    query = urllib.parse.urlencode(
        {"dhanClientId": client_id, "pin": pin, "totp": totp_now(totp_secret)}
    )
    status, body = _post(GENERATE_URL + "?" + query)

    if status != 200:
        raise RuntimeError(
            "generateAccessToken failed with HTTP %s: %s — no token could be "
            "obtained. Check that TOTP is still enabled for this client under "
            "Dhan Web > DhanHQ Trading APIs." % (status, body[:500])
        )

    try:
        payload = json.loads(body)
    except ValueError:
        raise RuntimeError(
            "generateAccessToken returned HTTP 200 with a non-JSON body: %r" % body[:500]
        )

    access_token = payload.get("accessToken")
    if not access_token:
        # Dhan answers 200 with a {message, status} envelope for at least some
        # refusals. The body is the only thing that says which, and it carries
        # no token, so log it whole rather than just its keys.
        raise RuntimeError(
            "generateAccessToken returned HTTP 200 but no accessToken. Dhan "
            "said: %s" % body[:500]
        )

    # Recorded only so a timezone question can be answered from logs later.
    # Never used for arithmetic — see the module docstring.
    logger.info("generateAccessToken reported expiryTime=%r", payload.get("expiryTime"))
    return access_token


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def lambda_handler(event, context):
    """EventBridge Scheduler entry point.

    Raises on failure so the invocation is recorded as an error and the
    schedule's retry policy applies. Returns metadata only — never the token;
    consumers read that from the parameter.
    """
    client_id = os.environ["DHAN_CLIENT_ID"]
    pin = os.environ["DHAN_PIN"]
    totp_secret = os.environ["DHAN_TOTP_SECRET"]

    started = time.time()

    access_token = generate_token(client_id, pin, totp_secret)
    expires_at = token_expiry_epoch(access_token)
    record = write_stored_token(access_token, expires_at)

    result = {
        "status": "success",
        "source": "totp",
        "expires_at": expires_at,
        "expires_in_hours": round((expires_at - time.time()) / 3600, 2),
        "parameter": TOKEN_PARAMETER_NAME,
        "refreshed_at": record["refreshed_at"],
        "elapsed_seconds": round(time.time() - started, 2),
    }
    logger.info(
        "dhan token refreshed: %s (token %s...)", json.dumps(result), access_token[:12]
    )
    return result
