"""
Dhan Broker Auth — AWS Lambda function

Mints a DhanHQ v2 access token and stores it in SSM Parameter Store, so the
session functions never have to authenticate themselves.

    weekday? ──no──▶ skip
       │yes
    holiday? ──yes──▶ DISABLE daily + intraday schedules ──▶ skip
       │no
    TOTP ──▶ POST /app/generateAccessToken ──▶ write /algo/dhan/token
                                          ├──▶ non-200 or no token ──▶ raise
                                          └──▶ ENABLE daily + intraday schedules

Trigger: EventBridge Scheduler, cron(0 8 ? * MON-FRI *) Asia/Kolkata — once
each weekday morning, before the 09:15 open. A token lives 24 hours, so the
08:00 token covers the whole session with hours to spare.

THIS FUNCTION DECIDES WHETHER THE DAY HAPPENS. It is the only thing that runs
before the session on every weekday, holiday included — a holiday IS a weekday,
so the MON-FRI cron still fires and the decision point is symmetric: disable on
a holiday, enable on a trading day. The session functions are therefore never
invoked on a holiday rather than invoked and skipping.

That concentration is deliberate and costs little, because this function is
already a hard dependency of the whole day: every consumer calls
read_token_record(), which RAISES on a missing or expired token. A morning
where auth fails is already a dead day, alarmed by error-notifier. Attaching
the schedule decision to it adds no new way to lose a session.

WHY A HOLIDAY IS AN ABSENT ROW. algo.trading_holiday stores closures only, so
"not in the table" means a normal session. A calendar nobody reseeded keeps the
system trading — a few no-op invocations — rather than making it go quiet,
which nothing here can detect: no alarm in this system can see a function that
was never invoked. See trading-calendar/README.md.

Why there is no renew path. /v2/RenewToken exists and would have let one TOTP
login carry a whole week, but it refuses tokens minted this way:

    HTTP 500  DH-905  INVALID_REQUEST
    "Renewal of token not allowed for this token type"

measured 2026-09-10. Renewal is only offered for tokens generated by hand from
Dhan Web. Seeding the parameter once from the web portal and renewing onward
does not rescue it either: the chain breaks every weekend, Monday falls back to
TOTP, and a TOTP-minted token cannot be renewed — so it degrades to this same
design after the first Saturday, having added a manual step on the way. The
branch was built, tested against the live API, and removed. Do not add it back
without new evidence from Dhan.

Weekends are skipped because nothing trades then; Monday simply mints a fresh
token like any other weekday.

Packaging notes:
  - stdlib, boto3 (pre-installed in the runtime), and the neon-db-driver +
    neon-access layers. THIS FUNCTION USED TO NEED NO LAYERS AT ALL, and the
    holiday read is what changed that: it now also needs NEON_CONNECTION_STRING
    and so ssm:GetParameter + kms:Decrypt, which had been removed here on the
    grounds that this function only writes. Both layer ARNs are pinned and must
    be repointed together when either is republished.
  - TOTP is implemented inline (RFC 6238, ~10 lines of hmac/struct) rather
    than pulling in pyotp, and the Dhan endpoint is called with urllib rather
    than the dhanhq SDK, which would drag in pandas/numpy.

Conventions:
  - expires_at is epoch seconds, read from the JWT's own `exp` claim. The
    API also returns an expiryTime string, but it carries no timezone marker
    and is IST — measured 2026-09-10, where exp=1789134580 (13:49:40 UTC) was
    reported as "2026-09-11T19:19:40.019". Parsing it as UTC is 5.5 hours too
    late, so it is logged for diagnostics and never used for arithmetic.
  - Nothing here logs or returns the token. Only its prefix and expiry are
    logged; consumers read the token from the parameter.
"""

import base64
import datetime
import hashlib
import hmac
import json
import logging
import os
import struct
import time
import urllib.error
import urllib.parse
import urllib.request

import boto3

from neon_access import (
    SSL_CONTEXT,
    connect,
    get_parameter,
    read_neon_connection_string,
    today_ist,
)

logger = logging.getLogger()
logger.setLevel(logging.INFO)

GENERATE_URL = os.environ.get(
    "DHAN_GENERATE_TOKEN_URL",
    "https://auth.dhan.co/app/generateAccessToken",
)

TOKEN_PARAMETER_NAME = os.environ.get("TOKEN_PARAMETER_NAME", "/algo/dhan/token")

# The same parameter daily-market-sentiment and error-notifier read. One chat,
# one bot: a holiday notice belongs beside the daily brief it replaces.
TELEGRAM_PARAMETER_NAME = os.environ.get(
    "TELEGRAM_PARAMETER_NAME", "/algo/telegram/brief"
)

# How far ahead the holiday notice looks for the next session. Generous: the
# longest run of weekday closures here is two (Diwali 2025, 21-22 October).
NEXT_SESSION_HORIZON_DAYS = 10

HTTP_TIMEOUT_SECONDS = int(os.environ.get("HTTP_TIMEOUT_SECONDS", "30"))

# RFC 6238 defaults, which is what Dhan's authenticator enrolment issues.
TOTP_STEP_SECONDS = 30
TOTP_DIGITS = 6

HOLIDAY_TABLE = "algo.trading_holiday"

# The schedules this function switches on and off. NAMES, not ARNs: the
# Scheduler API addresses a schedule by name within its group. Configured
# rather than hardcoded so renaming a schedule is an environment change.
#
# THIS FUNCTION'S OWN SCHEDULE MUST NEVER APPEAR HERE. It is the heartbeat that
# makes the decision, so a run that switched it off could never switch it back
# on — the system would stay dark until someone noticed by hand.
MANAGED_SCHEDULES = [
    name.strip()
    for name in os.environ.get(
        "MANAGED_SCHEDULE_NAMES", "daily-market-sentiment,intraday-data-loader"
    ).split(",")
    if name.strip()
]
SCHEDULE_GROUP = os.environ.get("SCHEDULE_GROUP_NAME", "default")

# Reused across warm invocations; creating a boto3 client is not cheap.
_ssm = boto3.client("ssm")
_scheduler = boto3.client("scheduler")


# ---------------------------------------------------------------------------
# TOTP — RFC 6238, SHA-1, 6 digits, 30-second step.
#
# Inlined rather than imported so the package stays stdlib-only. Verified
# against the RFC 6238 test vectors (T=59 -> 287082, T=1111111109 -> 081804)
# using the secret "12345678901234567890".
# ---------------------------------------------------------------------------
def totp_now(secret_b32, at=None):
    """Current TOTP code for a base32 authenticator secret."""
    secret = secret_b32.strip().replace(" ", "").upper()
    secret += "=" * (-len(secret) % 8)
    key = base64.b32decode(secret)

    counter = int(at if at is not None else time.time()) // TOTP_STEP_SECONDS
    digest = hmac.new(key, struct.pack(">Q", counter), hashlib.sha1).digest()

    offset = digest[-1] & 0x0F
    code = struct.unpack(">I", digest[offset : offset + 4])[0] & 0x7FFFFFFF
    return str(code % (10**TOTP_DIGITS)).zfill(TOTP_DIGITS)


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------
def _post(url):
    """POST with an empty body. Returns (status, body_text).

    No Content-Type is set: the endpoint takes its parameters in the query
    string and no body, and declaring application/json on a zero-length body
    is what earned a DH-905 "missing required fields" from Dhan's auth API.
    """
    request = urllib.request.Request(url, method="POST", data=b"")
    try:
        with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
            return response.status, response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode("utf-8", "replace")


def token_expiry_epoch(access_token):
    """Epoch seconds from the JWT's `exp` claim.

    Raises if the claim cannot be read. Storing a token whose expiry we had to
    guess is exactly the silent wrongness the fail-loudly rule exists to stop:
    daily-market-sentiment keys its freshness check off this number, so a wrong
    value would keep a dead token in circulation without anything reporting it.
    """
    try:
        payload = access_token.split(".")[1]
        payload += "=" * (-len(payload) % 4)
        claims = json.loads(base64.urlsafe_b64decode(payload))
    except (IndexError, ValueError, TypeError) as exc:
        raise RuntimeError(
            "Could not decode the access token as a JWT, so its expiry is "
            "unknown. Dhan may have changed the token format — check the "
            "response shape before trusting anything stored."
        ) from exc

    exp = claims.get("exp")
    if not isinstance(exp, int):
        raise RuntimeError(
            "Access token JWT carries no usable `exp` claim (got %r). Refusing "
            "to store a token with a guessed expiry." % (exp,)
        )
    return exp


# ---------------------------------------------------------------------------
# Parameter Store
# ---------------------------------------------------------------------------
def write_stored_token(access_token, expires_at):
    """Persist the token as a single JSON blob.

    One parameter rather than two so the token and its expiry cannot drift
    apart: a torn write leaving a new token beside an old expiry would look
    healthy and behave wrongly.
    """
    record = {
        "access_token": access_token,
        "expires_at": expires_at,
        "refreshed_at": int(time.time()),
        "source": "totp",
    }
    _ssm.put_parameter(
        Name=TOKEN_PARAMETER_NAME,
        Value=json.dumps(record),
        Type="SecureString",
        Overwrite=True,
    )
    return record


# ---------------------------------------------------------------------------
# Dhan auth
# ---------------------------------------------------------------------------
def generate_token(client_id, pin, totp_secret):
    """Mint a token from client id + PIN + TOTP.

    This is the only way in, so any failure here is terminal and raises.
    """
    query = urllib.parse.urlencode(
        {"dhanClientId": client_id, "pin": pin, "totp": totp_now(totp_secret)}
    )
    status, body = _post(GENERATE_URL + "?" + query)

    if status != 200:
        raise RuntimeError(
            "generateAccessToken failed with HTTP %s: %s — no token could be "
            "obtained. Check that TOTP is still enabled for this client under "
            "Dhan Web > DhanHQ Trading APIs." % (status, body[:500])
        )

    try:
        payload = json.loads(body)
    except ValueError:
        raise RuntimeError(
            "generateAccessToken returned HTTP 200 with a non-JSON body: %r" % body[:500]
        )

    access_token = payload.get("accessToken")
    if not access_token:
        # Dhan answers 200 with a {message, status} envelope for at least some
        # refusals. The body is the only thing that says which, and it carries
        # no token, so log it whole rather than just its keys.
        raise RuntimeError(
            "generateAccessToken returned HTTP 200 but no accessToken. Dhan "
            "said: %s" % body[:500]
        )

    # Recorded only so a timezone question can be answered from logs later.
    # Never used for arithmetic — see the module docstring.
    logger.info("generateAccessToken reported expiryTime=%r", payload.get("expiryTime"))
    return access_token


# ---------------------------------------------------------------------------
# Trading calendar
# ---------------------------------------------------------------------------
def holiday_for(conn, trade_date):
    """The holiday on `trade_date`, or None when it is a normal session.

    A ROW MEANS CLOSED; NO ROW MEANS A NORMAL SESSION. algo.trading_holiday
    stores closures only, so "absent" is both the common answer and the
    permissive one — a calendar nobody reseeded keeps the system trading
    instead of making it go quiet. That asymmetry is the point, and the
    reasoning is in trading-calendar/README.md.

    Returns the description where one is known. Most rows have none: the seed
    source publishes dates without names, so the label is for humans reading
    logs, never for logic.
    """
    cursor = conn.cursor()
    cursor.execute(
        f"SELECT description FROM {HOLIDAY_TABLE} WHERE trade_date = %s",
        (trade_date,),
    )
    row = cursor.fetchone()
    if row is None:
        return None
    return row[0] or "unnamed holiday"


def next_trading_day(conn, after):
    """The next weekday that is not a stored closure, or None.

    For the holiday notice only — nothing decides anything on this. It answers
    the one question a holiday raises ("when do we resume"), and it answers it
    the same way the gate does: a weekday with no row is a session.

    None means the horizon ran out, which in practice means the calendar has
    not been reseeded. The notice says so rather than inventing a date.
    """
    start = after + datetime.timedelta(days=1)
    end = start + datetime.timedelta(days=NEXT_SESSION_HORIZON_DAYS)

    cursor = conn.cursor()
    cursor.execute(
        f"SELECT trade_date FROM {HOLIDAY_TABLE} "
        "WHERE trade_date >= %s AND trade_date <= %s",
        (start, end),
    )
    closed = {row[0] for row in cursor.fetchall()}

    day = start
    while day <= end:
        if day.weekday() < 5 and day not in closed:
            return day
        day += datetime.timedelta(days=1)
    return None


# ---------------------------------------------------------------------------
# Telegram
# ---------------------------------------------------------------------------
def format_holiday_notice(today, holiday, next_session, schedules):
    """The holiday message. Plain text, same chat as the daily brief."""
    lines = [
        f"Market holiday - {today:%a %d %b %Y}",
        "",
        holiday,
        "",
        "No access token minted.",
        "Session schedules disabled:",
    ]
    lines += [f"  {name} ({result})" for name, result in schedules.items()]
    lines += [""]
    if next_session:
        lines.append(f"Next session: {next_session:%a %d %b %Y}")
    else:
        # Only reachable when the calendar has run out of rows, which is worth
        # saying out loud - it is the one failure this design cannot see.
        lines.append(
            f"Next session: unknown - no open weekday found in the next "
            f"{NEXT_SESSION_HORIZON_DAYS} days. The holiday calendar may need "
            f"reseeding."
        )
    return "\n".join(lines)


def send_telegram(text):
    """Deliver one message. Raises if Telegram refuses it.

    Called only AFTER the schedules are disabled. The notice is courtesy; the
    gate is the job, and a Telegram outage must not leave the schedules armed
    on a holiday.
    """
    config = json.loads(get_parameter(TELEGRAM_PARAMETER_NAME))
    token, chat_id = config.get("bot_token"), config.get("chat_id")
    if not token or not chat_id:
        raise RuntimeError(
            f"{TELEGRAM_PARAMETER_NAME} must hold bot_token and chat_id"
        )

    payload = urllib.parse.urlencode(
        {"chat_id": str(chat_id), "text": text, "disable_web_page_preview": "true"}
    ).encode()
    request = urllib.request.Request(
        f"https://api.telegram.org/bot{token}/sendMessage", data=payload, method="POST"
    )
    with urllib.request.urlopen(
        request, timeout=HTTP_TIMEOUT_SECONDS, context=SSL_CONTEXT
    ) as response:
        body = json.loads(response.read().decode())
    if not body.get("ok"):
        raise RuntimeError(f"telegram refused the message: {body}")
    logger.info("telegram holiday notice delivered to chat %s", chat_id)


# ---------------------------------------------------------------------------
# EventBridge Scheduler
#
# UPDATE IS A REPLACE, NOT A PATCH. Scheduler has no EnableSchedule /
# DisableSchedule pair — that is EventBridge Rules, a different service with a
# different API. Every field not sent back to UpdateSchedule is dropped, so a
# hand-built payload silently discards whatever the schedule was created with:
# its timezone, its retry policy, its flexible time window. The definition is
# therefore read with GetSchedule and returned whole, with only State changed.
# ---------------------------------------------------------------------------
# Present in a GetSchedule response and rejected by UpdateSchedule.
_READ_ONLY_SCHEDULE_KEYS = (
    "Arn",
    "CreationDate",
    "LastModificationDate",
    "ResponseMetadata",
)


def set_schedule_state(name, state):
    """Switch one schedule to ENABLED or DISABLED. Returns what it did."""
    definition = _scheduler.get_schedule(Name=name, GroupName=SCHEDULE_GROUP)
    current = definition.get("State")
    if current == state:
        logger.info("schedule %s already %s", name, state)
        return "unchanged"

    payload = {
        key: value
        for key, value in definition.items()
        if key not in _READ_ONLY_SCHEDULE_KEYS
    }
    payload["State"] = state
    _scheduler.update_schedule(**payload)
    logger.info("schedule %s %s -> %s", name, current, state)
    return "updated"


def set_managed_schedules(state):
    """Switch every managed schedule.

    Any failure propagates. A schedule left in the wrong state is invisible,
    and the two directions are not equally bad: enabled-when-it-should-be-off
    wastes a few no-op invocations, while disabled-when-it-should-be-on costs
    the entire session and alarms nothing, because no alarm here can see a
    function that was never invoked. Raising is the only thing that reports it.
    """
    return {name: set_schedule_state(name, state) for name in MANAGED_SCHEDULES}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def lambda_handler(event, context):
    """EventBridge Scheduler entry point.

    Raises on failure so the invocation is recorded as an error and the
    schedule's retry policy applies. Returns metadata only — never the token;
    consumers read that from the parameter.
    """
    started = time.time()
    today = today_ist()

    # Only reachable by hand: the cron is MON-FRI. The session schedules are
    # MON-FRI too, so a weekend run has nothing to switch and mints no token.
    if today.weekday() >= 5:
        logger.info("%s is a %s - not a trading day", today, today.strftime("%A"))
        return {
            "status": "skipped_non_trading_day",
            "date": today.isoformat(),
            "reason": "weekend",
        }

    conn = connect(read_neon_connection_string())
    try:
        holiday = holiday_for(conn, today)
        # Read on the same connection rather than reopening one for the
        # notice: Neon autosuspends, and this is the cold wake-up of the day.
        next_session = next_trading_day(conn, today) if holiday else None
    finally:
        try:
            conn.close()
        except Exception:
            pass

    if holiday:
        # Schedules go off FIRST, and no token is minted: nothing will run
        # today that could use one, and it would be long expired before the
        # next session anyway. The notice comes after, because the gate is the
        # job — a Telegram outage must not leave the schedules armed.
        schedules = set_managed_schedules("DISABLED")
        logger.info("%s is a holiday (%s) - session schedules disabled", today, holiday)
        send_telegram(format_holiday_notice(today, holiday, next_session, schedules))
        return {
            "status": "skipped_non_trading_day",
            "date": today.isoformat(),
            "reason": "holiday",
            "holiday": holiday,
            "next_session": next_session.isoformat() if next_session else None,
            "schedules": schedules,
        }

    # Read here rather than at the top so a holiday still disables the
    # schedules on a day when one of these is missing.
    client_id = os.environ["DHAN_CLIENT_ID"]
    pin = os.environ["DHAN_PIN"]
    totp_secret = os.environ["DHAN_TOTP_SECRET"]

    access_token = generate_token(client_id, pin, totp_secret)
    expires_at = token_expiry_epoch(access_token)
    record = write_stored_token(access_token, expires_at)

    # Armed only once the token is stored. The other order would switch the
    # session schedules on against a token that was never refreshed, turning a
    # recoverable auth failure into a day of failing invocations.
    schedules = set_managed_schedules("ENABLED")

    result = {
        "status": "success",
        "source": "totp",
        "date": today.isoformat(),
        "schedules": schedules,
        "expires_at": expires_at,
        "expires_in_hours": round((expires_at - time.time()) / 3600, 2),
        "parameter": TOKEN_PARAMETER_NAME,
        "refreshed_at": record["refreshed_at"],
        "elapsed_seconds": round(time.time() - started, 2),
    }
    logger.info(
        "dhan token refreshed: %s (token %s...)", json.dumps(result), access_token[:12]
    )
    return result
